#!/usr/bin/env node

/**
 * Generate Article
 * Calls AI API to generate article content based on selected topic
 */

const fs = require('fs');
const path = require('path');
const fetch = require('node-fetch');

const TOPIC_FILE = path.join(__dirname, '..', 'selected-topic.json');
const ARTICLES_DIR = path.join(__dirname, '..', 'articles');
const PROMPT_FILE = path.join(__dirname, '..', 'prompts', 'article-generation.txt');
const COMPARATIVE_PROMPT = path.join(__dirname, '..', 'prompts', 'comparative-analysis.txt');
const FUN_PROMPT = path.join(__dirname, '..', 'prompts', 'fun-content.txt');

// Available themes for articles
const ARTICLE_THEMES = [
  'minimalist-clean',
  'neon-nights',
  'paper-ink',
  'ocean-breeze',
  'forest-calm',
  'sunset-vibes',
  'matrix-code',
  'cotton-candy',
  'industrial',
  'aurora'
];

function generateSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function generateDatePath() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  return path.join(year, month);
}

function calculateReadingTime(wordCount) {
  // Average reading speed: 200 words per minute
  return Math.ceil(wordCount / 200);
}

function getPromptForType(type) {
  switch (type) {
    case 'historical':
      return COMPARATIVE_PROMPT;
    case 'fun':
      return FUN_PROMPT;
    default:
      return PROMPT_FILE;
  }
}

async function callAI(prompt, topicData) {
  const apiKey = process.env.AI_API_KEY;
  const apiUrl = process.env.AI_API_URL || 'https://api.openai.com/v1/chat/completions';
  
  // If no API key, generate placeholder content
  if (!apiKey) {
    console.log('No AI_API_KEY found, generating placeholder content');
    return generatePlaceholderContent(topicData);
  }
  
  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are a professional blog writer creating engaging, well-researched articles for autonomousBLOG.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    });
    
    if (!response.ok) {
      throw new Error(`AI API error: ${response.status}`);
    }
    
    const data = await response.json();
    return data.choices[0].message.content;
    
  } catch (error) {
    console.error('AI API call failed:', error.message);
    return generatePlaceholderContent(topicData);
  }
}

function generatePlaceholderContent(topicData) {
  const { topic, type, tone, estimatedWords } = topicData;
  const theme = ARTICLE_THEMES[Math.floor(Math.random() * ARTICLE_THEMES.length)];
  const now = new Date();
  const slug = generateSlug(topic);
  
  return `---
title: "${topic}"
date: "${now.toISOString()}"
theme: "${theme}"
topic: "${topic}"
wordCount: ${estimatedWords}
readingTime: ${calculateReadingTime(estimatedWords)}
excerpt: "An autonomously generated article about ${topic}"
contentType: "${type}"
---

# ${topic}

*This article was autonomously generated by autonomousBLOG.*

## Introduction

This is a placeholder article generated because the AI API is not configured. 
The topic selected was: **${topic}**

## Content Type: ${type}

${type === 'news' ? 'This would contain the latest news and developments.' : 
  type === 'historical' ? 'This would contain a comparative analysis over time.' :
  'This would contain fun and entertaining content.'}

## Writing Style: ${tone}

The article would be written in a ${tone} tone, engaging readers with 
well-researched content about ${topic}.

## Conclusion

To enable real article generation:
1. Set up AI_API_KEY in your GitHub repository secrets
2. Optionally set AI_API_URL for custom endpoints

---
*Generated by autonomousBLOG on ${now.toUTCString()}*
`;
}

async function generateArticle() {
  // Load selected topic
  if (!fs.existsSync(TOPIC_FILE)) {
    throw new Error('No selected topic found. Run topic-selector.js first.');
  }
  
  const topicData = JSON.parse(fs.readFileSync(TOPIC_FILE, 'utf8'));
  console.log('Generating article for topic:', topicData.topic);
  
  // Load and prepare prompt
  const promptFile = getPromptForType(topicData.type);
  let prompt = fs.existsSync(promptFile) 
    ? fs.readFileSync(promptFile, 'utf8')
    : 'Write an article about {{TOPIC}}';
  
  // Replace placeholders
  const theme = ARTICLE_THEMES[Math.floor(Math.random() * ARTICLE_THEMES.length)];
  const now = new Date();
  
  prompt = prompt
    .replace('{{TOPIC}}', topicData.topic)
    .replace('{{ANGLE}}', topicData.angle || 'General exploration')
    .replace('{{TONE}}', topicData.tone || 'casual')
    .replace('{{WORD_COUNT}}', String(topicData.estimatedWords || 800))
    .replace('{{KEYWORDS}}', Array.isArray(topicData.keywords) 
      ? topicData.keywords.join(', ') 
      : topicData.keywords || 'technology')
    .replace('{{CONTENT_TYPE}}', topicData.type || 'article')
    .replace('{{DATE}}', now.toISOString())
    .replace('{{THEME}}', theme)
    .replace('{{HISTORICAL_DATE}}', new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString())
    .replace('{{CURRENT_DATE}}', now.toISOString());
  
  // Call AI to generate content
  let content = await callAI(prompt, topicData);
  
  // Ensure content has frontmatter
  if (!content.includes('---')) {
    content = `---
title: "${topicData.topic}"
date: "${now.toISOString()}"
theme: "${theme}"
topic: "${topicData.topic}"
wordCount: ${topicData.estimatedWords || 800}
readingTime: ${calculateReadingTime(topicData.estimatedWords || 800)}
excerpt: "An autonomously generated article"
contentType: "${topicData.type}"
---

${content}
`;
  }
  
  // Create article file
  const datePath = generateDatePath();
  const slug = generateSlug(topicData.topic);
  const articleDir = path.join(ARTICLES_DIR, datePath);
  const articleFile = path.join(articleDir, `${slug}.md`);
  
  // Ensure directory exists
  fs.mkdirSync(articleDir, { recursive: true });
  
  // Write article
  fs.writeFileSync(articleFile, content);
  console.log('Article created:', articleFile);
  
  // Clean up topic file
  if (fs.existsSync(TOPIC_FILE)) {
    fs.unlinkSync(TOPIC_FILE);
  }
  
  return { file: articleFile, theme };
}

// Main execution
async function main() {
  try {
    const result = await generateArticle();
    console.log('Article generation complete:', result.file);
  } catch (error) {
    console.error('Error generating article:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { generateArticle };
